// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumNeozQdQ7-f7QeaLtdOqkfypkBtq84E',
    appId: '1:402041696433:web:70d796b6502479632db290',
    messagingSenderId: '402041696433',
    projectId: 'daily-sync-f641e',
    authDomain: 'daily-sync-f641e.firebaseapp.com',
    storageBucket: 'daily-sync-f641e.firebasestorage.app',
    measurementId: 'G-606XJNG7C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0KuR_11IoHe9FcVnlt9gnT-g5SDnyQ0',
    appId: '1:402041696433:android:9e28ef52e35086432db290',
    messagingSenderId: '402041696433',
    projectId: 'daily-sync-f641e',
    storageBucket: 'daily-sync-f641e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB74QxL2U7_kymiwoFUXV6-fL1g1J7oMQU',
    appId: '1:402041696433:ios:384c3cb26fd040cc2db290',
    messagingSenderId: '402041696433',
    projectId: 'daily-sync-f641e',
    storageBucket: 'daily-sync-f641e.firebasestorage.app',
    iosBundleId: 'com.example.dailySync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB74QxL2U7_kymiwoFUXV6-fL1g1J7oMQU',
    appId: '1:402041696433:ios:384c3cb26fd040cc2db290',
    messagingSenderId: '402041696433',
    projectId: 'daily-sync-f641e',
    storageBucket: 'daily-sync-f641e.firebasestorage.app',
    iosBundleId: 'com.example.dailySync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBumNeozQdQ7-f7QeaLtdOqkfypkBtq84E',
    appId: '1:402041696433:web:ac1e8452cb1d1fc32db290',
    messagingSenderId: '402041696433',
    projectId: 'daily-sync-f641e',
    authDomain: 'daily-sync-f641e.firebaseapp.com',
    storageBucket: 'daily-sync-f641e.firebasestorage.app',
    measurementId: 'G-H9KL1VSB6B',
  );
}
